# Generated by Django 2.2.19 on 2021-04-09 19:04

import aplic.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_caixa', models.IntegerField(verbose_name='Código da caixa')),
                ('quantidade_caixas', models.IntegerField(verbose_name='Total de caixas')),
                ('peso_total_caixa', models.FloatField(verbose_name='Peso total da caixa')),
            ],
            options={
                'verbose_name': 'Caixa de Transporte',
                'verbose_name_plural': 'Caixas de Transporte',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=50, verbose_name='Rua')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('estado', models.CharField(max_length=40, verbose_name='Estado')),
                ('complemento', models.CharField(max_length=10, verbose_name='Complemento')),
                ('numero', models.IntegerField(verbose_name='Número')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Frete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=7, verbose_name='Valor')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Endereco')),
            ],
            options={
                'verbose_name': 'Frete',
                'verbose_name_plural': 'Fretes',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('telefone', models.CharField(help_text='DD NNNNN-NNNN', max_length=11, verbose_name='Número celular')),
                ('cargo', models.CharField(choices=[('Motorista', 'Motorista'), ('Estoquista', 'Estoquista'), ('Gerente', 'Gerente')], max_length=40, verbose_name='Cargo')),
                ('foto', stdimage.models.StdImageField(blank=True, null=True, upload_to=aplic.models.get_file_path, verbose_name='Foto')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Endereco')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnh', models.CharField(max_length=11, verbose_name='CNH')),
                ('salario', models.CharField(max_length=10, verbose_name='Salário')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Funcionario')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Coxa', 'Coxa'), ('Peito', 'Peito'), ('Sobrecoxa', 'Sobrecoxa'), ('Asa', 'Asa')], max_length=20, verbose_name='Código da caixa')),
                ('codigo_produto', models.IntegerField(verbose_name='Código do produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Revendedora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=15, verbose_name='CNPJ')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Endereco')),
            ],
            options={
                'verbose_name': 'Revendedora',
                'verbose_name_plural': 'Revendedoras',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_venda', models.IntegerField(verbose_name='Código da venda')),
                ('valor_total_vendido', models.IntegerField(verbose_name='Valor total da venda')),
                ('codigo_frete', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Frete')),
                ('codigo_revendedora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Revendedora')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, verbose_name='Placa')),
                ('cor', models.CharField(max_length=15, verbose_name='Cor')),
                ('motorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.Motorista')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('codigo_pedido', models.IntegerField(verbose_name='Código do pedido')),
                ('status', models.CharField(choices=[('Pedido aceito', 'Pedido aceito'), ('Pedido recusado', 'Pedido recusado')], max_length=20, verbose_name='Status')),
                ('valor_total_pedido', models.FloatField(verbose_name='Valor total do pedido')),
                ('codigo_caixa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.CaixaTransporte')),
                ('codigo_venda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Venda')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('salario', models.CharField(max_length=10, verbose_name='Salário')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Funcionario')),
            ],
            options={
                'verbose_name': 'Gerente',
                'verbose_name_plural': 'Gerentes',
            },
        ),
        migrations.CreateModel(
            name='Estoquista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('salario', models.CharField(max_length=10, verbose_name='Salário')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Funcionario')),
            ],
            options={
                'verbose_name': 'Estoquista',
                'verbose_name_plural': 'Estoquistas',
            },
        ),
        migrations.AddField(
            model_name='caixatransporte',
            name='codigo_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Produto'),
        ),
    ]
