# Generated by Django 2.2.19 on 2021-04-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='disponibilidade',
            field=models.BooleanField(default=True, verbose_name='Disponibilidade'),
            preserve_default=False,
        ),
    ]
