# Generated by Django 2.2.19 on 2021-04-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('Coxa', 'Coxa'), ('Peito', 'Peito'), ('Sobrecoxa', 'Sobrecoxa'), ('Asa', 'Asa')], max_length=20, verbose_name='Tipo do produto'),
        ),
    ]
