# Generated by Django 2.2.19 on 2021-04-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_auto_20210408_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(help_text='DD NNNNN-NNNN', max_length=11, verbose_name='Número celular'),
        ),
    ]
