# Generated by Django 2.2.19 on 2021-04-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_produto_disponibilidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='pedido_id',
        ),
        migrations.AddField(
            model_name='venda',
            name='pedido_id',
            field=models.ManyToManyField(to='aplic.Pedido'),
        ),
    ]
