# Generated by Django 2.2.19 on 2021-04-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_pedido_venda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
