# Generated by Django 2.2.19 on 2021-04-18 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_auto_20210417_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_entrega', models.CharField(max_length=7, verbose_name='Valor')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Endereco')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Motorista')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
            },
        ),
        migrations.RemoveField(
            model_name='venda',
            name='cnh_motorista',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='placa_veiculo',
        ),
        migrations.DeleteModel(
            name='Frete',
        ),
        migrations.AddField(
            model_name='entrega',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Venda'),
        ),
    ]
