# Generated by Django 2.2.19 on 2021-04-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_auto_20210417_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='valor_entrega',
            field=models.CharField(max_length=7, verbose_name='Valor frete'),
        ),
    ]
