# Generated by Django 2.2.19 on 2021-04-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0005_auto_20210418_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='endereco',
        ),
        migrations.AddField(
            model_name='entrega',
            name='data_entrega',
            field=models.DateField(default='2021-07-07', verbose_name='Data da Entrega'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrega',
            name='melhor_horario',
            field=models.TimeField(default='08:08', verbose_name='Melhor horário para entrega'),
            preserve_default=False,
        ),
    ]
