# Generated by Django 2.2.19 on 2021-04-18 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0006_auto_20210418_0013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Veiculo',
        ),
    ]
